using System;
using System.Collections.Generic;

namespace LotroTrGemini;

/// <summary>Reviewed Turkish names for pet, mount and housing collections.</summary>
public static class ManualCollectionText
{
    private static readonly Dictionary<string, string> Exact = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        { "Able Ice-shore Fisher[v]", "Usta Buz Kıyısı Balıkçısı[v]" },
        { "Adorable Sand Worm", "Sevimli Kum Solucan" },
        { "Adorable Sickle-fly", "Sevimli Orak Sineği" },
        { "Adventurous Lurker", "Maceracı Pusucu" },
        { "Affable Grodbog Queen[fv]", "Cana Yakın Grodbog Kraliçesi[fv]" },
        { "Agarnaith Crawler", "Agarnaith Sürüngeni" },
        { "Agarnaith Snake", "Agarnaith Yılan" },
        { "Agarnaith Wormling", "Agarnaith Solucancığı" },
        { "Aggressive Grodbog Queen[fv]", "Saldırgan Grodbog Kraliçesi[fv]" },
        { "Alabaster Donkey", "Kaymaktaşı Eşeği" },
        { "Albino Jerboa", "Albino Arap Tavşanı" },
        { "Amber Fire-fly", "Kehribar Ateşböceği" },
        { "Amethyst Drakeling[v]", "Ametist Ejderha Yavrusu[v]" },
        { "Amethyst Neekerbreeker", "Ametist Neekerböceği" },
        { "Ametrine Drakeling[v]", "Ametrin Ejderha Yavrusu[v]" },
        { "Anniversary Celebration Corgi", "Yıldönümü Kutlama Korgi" },
        { "Anniversary Celebration Goat", "Yıldönümü Kutlaması Keçisi" },
        { "Anniversary Celebration Pig", "Yıldönümü Kutlama Domuz" },
        { "Anniversary Medium Carry-all Selection Box[v]", "Yıldönümü Orta Çoklu Çanta Seçim Kutusu[v]" },
        { "Anniversary Small Carry-all Selection Box[v]", "Yıldönümü Küçük Çoklu Çanta Seçim Kutusu[v]" },
        { "Armoured Desert Wasp[v]", "Zırhlı Çöl Eşekarısı[v]" },
        { "Armoured Scorpion[v]", "Zırhlı Akrep[v]" },
        { "Ash Frog", "Kül Kurbağa" },
        { "Ashen Eagle", "Küllü Kartal" },
        { "Aurochs Calf", "Yaban Sığırı Buzağısı" },
        { "Autumn Aurochs", "Sonbahar Yaban Sığırı" },
        { "Autumn Heartwood Stag", "Sonbahar Özodun Geyik" },
        { "Baby Camel[e]", "Yavru Deve[e]" },
        { "Badger", "Porsuk" },
        { "Baker's Delight Cub[e]", "Fırıncının Neşe Yavrusu[e]" },
        { "Banded Snake", "Şeritli Yılan" },
        { "Banquet Decoration - Selection Box[e]", "Ziyafet Dekorasyonu Seçim Kutusu[e]" },
        { "Barrel of Cream[e]", "Krema Fıçısı[e]" },
        { "Battle-adorned Pig", "Savaş Süslemeli Domuz" },
        { "Battle-worn Steed of the White City", "Beyaz Şehrin Savaş Yorgunu Küheylanı" },
        { "Battle-worn Worm[e]", "Savaş Yorgunu Solucan[e]" },
        { "Beaver", "Kunduz" },
        { "Beehive Recipe[e]", "Arı Kovanı Tarifi[e]" },
        { "Beer-loving Badgers Kite", "Bira Seven Porsuklar Uçurtması" },
        { "Before the Shadow Ultimate Carry-all Selection Box[e]", "Gölgeden Önce Nihai Çoklu Çanta Seçim Kutusu[e]" },
        { "Bench - Vales of Anduin Recipe[e]", "Anduin Vadileri Bankı Tarifi[e]" },
        { "Beorn's Table Recipe[e]", "Beorn'un Masası Tarifi[e]" },
        { "Big Blue Carpenter Bee", "Büyük Mavi Marangoz Arısı" },
        { "Big Bumblebee", "Büyük Bombus Arısı" },
        { "Big Honey Bee", "Büyük Bal Arısı" },
        { "Big Kid", "Büyük Oğlak" },
        { "Big Wasp", "Büyük Eşekarısı" },
        { "Birdfeeder Recipe[e]", "Kuş Yemliği Tarifi[e]" },
        { "Black Bat", "Kara Yarasa" },
        { "Black Bear Cub", "Kara Ayı Yavru" },
        { "Black Bull", "Kara Boğa" },
        { "Black Cat", "Kara Kedi" },
        { "Black Cobra[e]", "Kara Kobra[e]" },
        { "Black Draught Horse", "Kara Yük Atı" },
        { "Black Huorn with Honeycomb", "Petekli Kara Huorn" },
        { "Black Marble Wolf-dog", "Kara Mermer Kurt Köpeği" },
        { "Black Mastiff", "Kara Mastif" },
        { "Black Miniature Draught Horse", "Kara Minyatür Yük Atı" },
        { "Black Peacock", "Kara Tavuskuşu" },
        { "Black Peahen", "Kara Dişi Tavuskuşu" },
        { "Black Pig", "Kara Domuz" },
        { "Black Rabbit", "Kara Tavşan" },
        { "Black Swan[e]", "Kara Kuğu[e]" },
        { "Black Truffle Recipe[e]", "Kara Yer Mantarı Tarifi[e]" },
        { "Black Wolf-dog", "Kara Kurt Köpeği" },
        { "Black-beak Cave-claw[e]", "Kara Gagalı Mağara Pençesi[e]" },
        { "Black-foot Chicken[e]", "Kara Ayaklı Tavuk[e]" },
        { "Black-wing Kite", "Kara Kanatlı Uçurtma" },
        { "Blight Frog", "Veba Kurbağa" },
        { "Blonde Corgi", "Sarışın Korgi" },
        { "Blood Craban", "Kan Craban" },
        { "Blood Scorpion[e]", "Kan Akrep[e]" },
        { "Blood-red Bat", "Kan Kırmızısı Yarasa" },
        { "Blue Beetle", "Mavi Böcek" },
        { "Blue Chimes Recipe[e]", "Mavi Çanlar Tarifi[e]" },
        { "Blue Firefly", "Mavi Ateşböceği" },
        { "Blue Lizard", "Mavi Kertenkele" },
        { "Blue Peacock", "Mavi Tavuskuşu" },
        { "Blue Peahen", "Mavi Dişi Tavuskuşu" },
        { "Bog-lurker Buddy", "Bataklık Pusucusu Dostu" },
        { "Box of Mushroom Hunter's Walls[s]", "Mantar Avcısının Duvarları Kutusu[s]" },
        { "Brick Corgi", "Tuğla Korgi" },
        { "Bright Grodbog Protector[e]", "Parlak Grodbog Koruyucusu[e]" },
        { "Brown Bat", "Kahverengi Yarasa" },
        { "Brown Bear Cub", "Kahverengi Ayı Yavru" },
        { "Brown Cow", "Kahverengi İnek" },
        { "Brown Fox", "Kahverengi Tilki" },
        { "Brown Jerboa", "Kahverengi Arap Tavşanı" },
        { "Brown Marble Wolf-dog", "Kahverengi Mermer Kurt Köpeği" },
        { "Brown Mûmak Calf[e]", "Kahverengi Mûmak Buzağısı[e]" },
        { "Brown Oryx[e]", "Kahverengi Oryx[e]" },
        { "Brown Pig", "Kahverengi Domuz" },
        { "Brown Rabbit", "Kahverengi Tavşan" },
        { "Brown Sheep", "Kahverengi Koyun" },
        { "Brown Snake", "Kahverengi Yılan" },
        { "Brown Squirrel", "Kahverengi Sincap" },
        { "Brown Wolf-dog", "Kahverengi Kurt Köpeği" },
        { "Buff Donkey", "Açık Kahverengi Eşek" },
        { "Bumblebee Kite", "Bombus Arısı Uçurtması" },
        { "Burdened Mûmak Calf[e]", "Yüklü Mûmak Buzağısı[e]" },
        { "Butterflies", "Kelebekler" },
        { "Calf of High-land Pastures[s]", "Yayla Meralarının Buzağısı[s]" },
        { "Caravan Trade Goods Camel[e]", "Kervan Ticaret Devesi[e]" },
        { "Cart Pony", "Araba Midillisi" },
        { "Cask-laden Donkey", "Fıçı Yüklü Eşek" },
        { "Cave Slug", "Mağara Sümüklüböcek" },
        { "Charming Feline", "Büyüleyici Kedigiller" },
        { "Chestnut Corgi", "Kestane Korgi" },
        { "Chestnut Sand Worm", "Kestane Kum Solucan" },
        { "Chipmunk", "Çizgili Sincap" },
        { "Cinder Hawk", "Kor Şahin" },
        { "Cobalt Grodbog Protector[e]", "Kobalt Grodbog Koruyucusu[e]" },
        { "Cobra[e]", "Kobra[e]" },
        { "Copper Goat", "Bakır Keçi" },
        { "Copper Nether-hound", "Bakır Öte Tazısı" },
        { "Copper Scorpion[e]", "Bakır Akrep[e]" },
        { "Copper Zizanu[e]", "Bakır Zizanu[e]" },
        { "Copper-back Frog", "Bakır Sırtlı Kurbağa" },
        { "Corrupted Craban", "Bozulmuş Craban" },
        { "Corsairs of Umbar Ultimate Carry-all Selection Box[e]", "Umbar Korsanları Nihai Çoklu Çanta Seçim Kutusu[e]" },
        { "Cozy Den Housing Collection[e]", "Samimi İn Ev Koleksiyonu[e]" },
        { "Cozy Grey Cat", "Şirin Gri Kedi" },
        { "Cozy Tabby Cat", "Şirin Tekir Kedi" },
        { "Crafty Worm[e]", "Usta Solucan[e]" },
        { "Craggy Slug", "Kayalık Sümüklüböcek" },
        { "Cream Corgi", "Krem Korgi" },
        { "Crimson Deep-claw Whelp[e]", "Kızıl Derin Pençe Yavrusu[e]" },
        { "Crimson Dragon Kite", "Kızıl Ejderha Uçurtması" },
        { "Crocodile Hatchling", "Timsah Yavrusu" },
        { "Crystal Grim", "Kristal Kasvetlisi" },
        { "Crystal Spider", "Kristal Örümcek" },
        { "Curious Slug", "Meraklı Sümüklüböcek" },
        { "Daffodil Celebration Kid[e]", "Nergis Kutlaması Oğlağı[e]" },
        { "Dale Calf", "Dale Buzağısı" },
        { "Dappled Grey Draught Horse", "Benekli Gri Yük Atı" },
        { "Dappled Grey Miniature Draught Horse", "Benekli Gri Minyatür Yük Atı" },
        { "Dappled Tri-colour Cat", "Benekli Üç Renkli Kedi" },
        { "Dark Grodbog Queen[f]", "Koyu Grodbog Kraliçesi[f]" },
        { "Dashing Dusky Parrot", "Atılgan Alacakaranlık Papağan" },
        { "Dashing Feline", "Atılgan Kedigiller" },
        { "Death-light Scorpion[e]", "Ölüm Işığı Akrep[e]" },
        { "Decorated Goose", "Süslemeli Kaz" },
        { "Deep Emerald Snake", "Derin Zümrüt Yılan" },
        { "Deep-claw Whelp", "Derin Pençe Yavrusu" },
        { "Delving Nether-hound", "Derinlik Öte Tazısı" },
        { "Desert Slime[e]", "Çöl Balçığı[e]" },
        { "Diamondback Snake", "Elmas Sırtlı Yılan" },
        { "Diligent Mûmak Calf[e]", "Çalışkan Mûmak Buzağısı[e]" },
        { "Distant Cousin", "Uzak Kuzen" },
        { "Dol Guldur Prison Housing Collection[e]", "Dol Guldur Hapishanesi Ev Koleksiyonu[e]" },
        { "Dorking Chicken[e]", "Dorking Tavuk[e]" },
        { "Dragon's Hoard Housing Collection[e]", "Ejderhanın Hazinesi Ev Koleksiyonu[e]" },
        { "Dread-filled Dwelling Housing Collection[e]", "Korku Dolu Mesken Ev Koleksiyonu[e]" },
        { "Dusk-wing Kite", "Alacakaranlık Kanadı Uçurtma" },
        { "Dusky Grodbog Queen[f]", "Alacakaranlık Grodbog Kraliçesi[f]" },
        { "Dusky Nether-hound", "Alacakaranlık Öte Tazısı" },
        { "Dusky Parrot", "Alacakaranlık Papağan" },
        { "Dusty Shrew[e]", "Tozlu Sivrifare[e]" },
        { "Dusty Worm[e]", "Tozlu Solucan[e]" },
        { "Dwarrowgleam Shadowbox Recipe[e]", "Dwarrowgleam Gölge Kutusu Tarifi[e]" },
        { "Eager Beaver", "Hevesli Kunduz" },
        { "Eagle-Owl of the Flowering Sun[v]", "Çiçeklenen Güneşin Kartal Baykuşu[v]" },
        { "Eerie Apothecary Housing Collection[v]", "Tekinsiz Eczacı Ev Koleksiyonu[v]" },
        { "Elvish Furnishings (All) Bundle[v]", "Elf Döşemeleri (Tümü) Paketi[v]" },
        { "Elvish Outpost Housing Collection[v]", "Elf Karakolu Ev Koleksiyonu[v]" },
        { "Emerald Drakeling[v]", "Zümrüt Ejderha Yavrusu[v]" },
        { "Emerald Slime[v]", "Zümrüt Balçığı[v]" },
        { "Enchanted Vessel", "Büyülü Kap" },
        { "Evergreen Sickle-fly", "Daima Yeşil Orak Sineği" },
        { "Evergreen Wall Decorations - Selection Box[v]", "Daima Yeşil Duvar Dekorasyonları Seçim Kutusu[v]" },
        { "Faltharan's Steed", "Faltharan'ın Küheylanı" },
        { "Fangorn Huorn", "Fangorn Huornu" },
        { "Faroth", "Faroth Yoldaşı" },
        { "Feed-laden Donkey", "Yem Yüklü Eşek" },
        { "Feisty Wolverine", "Hırçın Rosomak" },
        { "Fennec Fox", "Fennek Tilki" },
        { "Ferocious Battle-kitten", "Vahşi Savaş Yavru Kedisi" },
        { "Fierce Hedgehog[e]", "Vahşi Kirpi[e]" },
        { "Fiery Blue Beetle", "Ateşli Mavi Böcek" },
        { "Fiery Desert Snake", "Ateşli Çöl Yılan" },
        { "Fiery Red Beetle", "Ateşli Kırmızı Böcek" },
        { "Fiery Yellow Beetle", "Ateşli Sarı Böcek" },
        { "Finely Carved Rallying Horn[E]", "İnce Oymalı Teşvik Borusu[E]" },
        { "Fire Grim", "Ateş Kasvetlisi" },
        { "Fire-fox Bandit", "Ateş Tilkisi Haydudu" },
        { "Fireworks Corgi", "Havai Fişekli Korgi" },
        { "Floating Lantern Decoration - Selection Box[e]", "Yüzen Fener Dekorasyonu Seçim Kutusu[e]" },
        { "Floral Kite", "Çiçekli Uçurtma" },
        { "Flying Fox", "Uçan Tilki" },
        { "Fog Frog", "Sis Kurbağası" },
        { "Forest Lantern Recipe[e]", "Orman Feneri Tarifi[e]" },
        { "Formal Corgi", "Resmî Korgi" },
        { "Friendly Bear Cub", "Dost Ayı Yavru" },
        { "Friendly Egret", "Dost Ak Balıkçıl" },
        { "Friendly Heron", "Dost Balıkçıl" },
        { "Friendly Stork", "Dost Leylek" },
        { "Frog", "Kurbağa" },
        { "Frost Aurochs", "Buzlu Yaban Sığırı" },
        { "Frost-tusk Youngling", "Buz Dişli Yavrusu" },
        { "Frosty Kite", "Buzlu Uçurtma" },
        { "Ghostly Cat[e]", "Hayaletimsi Kedi[e]" },
        { "Ginger Cat", "Zencefil Kedi" },
        { "Ginger Mûrai Herding Dog[e]", "Zencefil Mûrai Çoban Köpeği[e]" },
        { "Gloaming Kite", "Alacakaranlık Uçurtma" },
        { "Glorious Memories of Gondor Housing Collection[e]", "Gondor'un Şanlı Anıları Ev Koleksiyonu[e]" },
        { "Goat of the Forest-spirit", "Orman Ruhunun Keçisi" },
        { "Gold Housing Decorations of Yules Past - Selection Box[e]", "Geçmiş Yule'un Altın Ev Dekorasyonları Seçim Kutusu[e]" },
        { "Gold Zizanu[e]", "Altın Zizanu[e]" },
        { "Golden Barn Owl", "Altın Ahır Baykuşu" },
        { "Golden Bat", "Altın Yarasa" },
        { "Golden Cave-claw", "Altın Mağara Pençesi" },
        { "Golden Crystal Beetle", "Altın Kristal Böcek" },
        { "Golden Doe[f]", "Altın Dişi Geyik[f]" },
        { "Golden Dragon Kite", "Altın Ejderha Uçurtması" },
        { "Golden Drakeling[e]", "Altın Ejderha Yavrusu[e]" },
        { "Golden Fawn[e]", "Altın Geyik Yavrusu[e]" },
        { "Golden Grain Kite", "Altın Tahıl Uçurtması" },
        { "Golden Sheep", "Altın Koyun" },
        { "Golden Stag[m]", "Altın Geyik[m]" },
        { "Gondorian Scholar's Study Set[e]", "Gondor Bilgini Çalışma Seti[e]" },
        { "Goose", "Kaz" },
        { "Gorgoroth Crawler", "Gorgoroth Sürüngeni" },
        { "Gourd-lurker", "Kabak Pusucusu" },
        { "Grabby Crab", "Kapkaççı Yengeç" },
        { "Grant the Homestead Concert Dance Emote[e]", "Çiftlik Konser Dans İfadesini Ver[e]" },
        { "Greater River Hobbit Cosmetics[ps]", "Greater River Hobbit Kozmetikleri[ps]" },
        { "Green Beetle", "Yeşil Böcek" },
        { "Green Firefly", "Yeşil Ateşböceği" },
        { "Green Glow Worm", "Yeşil Işıltılı Solucan" },
        { "Green Peacock", "Yeşil Tavuskuşu" },
        { "Green Peahen", "Yeşil Dişi Tavuskuşu" },
        { "Green-back Cave-claw[e]", "Yeşil Sırtlı Mağara Pençesi[e]" },
        { "Green-beak Cave-claw[e]", "Yeşil Gagalı Mağara Pençesi[e]" },
        { "Grim", "Kasvetli Yoldaş" },
        { "Gundabad Mountain-mark[e]", "Gundabad Dağ İşareti[e]" },
        { "Gundabad Ukhrash", "Gundabad Ukhrash Yoldaşı" },
        { "Hallows-eve Kite", "Ölüler Gecesi Uçurtması" },
        { "Harbinger of the Sage's Storm", "Bilgenin Fırtına Habercisi" },
        { "Harmonious Falcon", "Uyumlu Doğan" },
        { "Harnessed Shepherd Dog", "Koşumlu Çoban Köpeği" },
        { "Harvest Revelry Kite", "Hasat Şenliği Uçurtması" },
        { "Harvest's Bounty Housing Collection[e]", "Hasat Bereketi Ev Koleksiyonu[e]" },
        { "Heather Hamster", "Funda Hamster" },
        { "Heavy Armour of the Vales Recipe[E]", "Vadilerin Ağır Zırh Tarifi[E]" },
        { "Hedgehog", "Kirpi" },
        { "Hedgehog and Hare Parade[e]", "Kirpi ve Yaban Tavşanı Geçidi[e]" },
        { "Helpful Deep-claw Whelp[e]", "Yardımsever Derin Pençe Yavrusu[e]" },
        { "Helpful Hound", "Yardımsever Tazı" },
        { "Herding Dog of the Rohirrim[e]", "Rohirrim Çoban Köpeği[e]" },
        { "Heroes of the Dwarf-halls Housing Collection[e]", "Cüce Salonlarının Kahramanları Ev Koleksiyonu[e]" },
        { "Heroic Deep Places Memoir Wardrobe Cosmetics[ps]", "Kahramanlık Derin Yerler Hatırası Gardırop Kozmetikleri[ps]" },
        { "Hewn Rallying Horn[E]", "Oymalı Teşvik Borusu[E]" },
        { "Homestead Defender Bundle[e]", "Çiftlik Savunucusu Paketi[e]" },
        { "Homesteader's Draught Horse", "Çiftlik Sahibinin Yük Atı" },
        { "Homesteader's Luxuriant Mithril Coffer[e]", "Homesteader's Gösterişli Mithril Sandık[e]" },
        { "Homesteader's Miniature Draught Horse", "Çiftlik Sahibinin Minyatür Yük Atı" },
        { "Homesteads and Harvests Enhanced Coffer", "Homesteads ve Harvests Geliştirilmiş Sandık" },
        { "Homesteads and Harvests Enhanced Cosmetics Coffer[e]", "Homesteads ve Harvests Geliştirilmiş Kozmetikleri Sandık[e]" },
        { "Homesteads and Harvests Luxuriant Coffer", "Homesteads ve Harvests Gösterişli Sandık" },
        { "Homesteads and Harvests Luxuriant Cosmetics Coffer[e]", "Homesteads ve Harvests Gösterişli Kozmetikleri Sandık[e]" },
        { "Homesteads and Harvests Simple Coffer", "Homesteads ve Harvests Basit Sandık" },
        { "Homesteads and Harvests Simple Cosmetics Coffer[e]", "Homesteads ve Harvests Basit Kozmetikleri Sandık[e]" },
        { "Honey Jar[e]", "Bal Kavanozu[e]" },
        { "Hopeful Swan Kite", "Umutlu Kuğu Uçurtması" },
        { "Horse of Bounty", "Armağan Atı" },
        { "Horse of the Autumn Sun", "Sonbahar Güneşi Atı" },
        { "Horse[e]", "At[e]" },
        { "Hound of Promised Allies[s]", "Vaat Edilen Müttefiklerin Tazısı[s]" },
        { "Humming Sunbird[e]", "Vızıldayan Güneşkuşu[e]" },
        { "Husky Wolf-dog", "Husky Kurt Köpeği" },
        { "Hutch[e]", "Kümes[e]" },
        { "Ice Salamander", "Buz Semenderi" },
        { "Icy Expeditions Sheep", "Buzlu Sefer Koyun" },
        { "Ill Omened Beast", "Uğursuz Yaratık" },
        { "Ill Omened Crab", "Uğursuz Uğursuz Yengeç" },
        { "Ill Omened Crawler", "Uğursuz Sürüngen" },
        { "Ill Omened Hound", "Uğursuz Tazı" },
        { "Ill Omened Jackal", "Uğursuz Uğursuz Çakal" },
        { "Ill Omened Snake", "Uğursuz Uğursuz Yılan" },
        { "Ill Omened Worm", "Uğursuz Solucan" },
        { "Imladris Visitors[ps]", "Ayrıkvadi Ziyaretçileri[ps]" },
        { "Incomparable Coffer of Gil-Galad[v]", "Eşsiz Sandık Gil-Galad[v]" },
        { "Incomparable Coffer of the Floating Lanterns[vs]", "Eşsiz Sandık Yüzen Lanterns[vs]" },
        { "Industrious Mûmak Calf[v]", "Çalışkan Mûmak Buzağısı[v]" },
        { "Injured Bat", "Yaralı Yarasa" },
        { "Ithilien Fox", "Ithilien Tilki" },
        { "Ivory Mûrai Herding Dog[v]", "Fildişi Mûrai Çoban Köpeği[v]" },
        { "Jade Speckled Snake", "Yeşim Benekli Yılan" },
        { "Jaunty Monkey[e]", "Neşeli Maymun[e]" },
        { "Jaunty Patron's Luxuriant Wardrobe Cosmetics[ps]", "Jaunty Patron's Gösterişli Gardırop Kozmetikleri[ps]" },
        { "Jerboa", "Arap Tavşanı" },
        { "Jingle Turtle[e]", "Çıngıraklı Kaplumbağa[e]" },
        { "Keepsakes of Belondor[p]", "Belondor Hatıraları[p]" },
        { "Kingdoms of Harad Large Carry-all Selection Box[e]", "Harad Krallıkları Büyük Çoklu Çanta Seçim Kutusu[e]" },
        { "Kite of the Sickle", "Orak Uçurtması" },
        { "Lantern Gourd-lurker", "Fener Kabak Pusucusu" },
        { "Large box of Cockscomb Recipe[e]", "Büyük Horozibiği Kutusu Tarifi[e]" },
        { "Large box of Gladdens Recipe[e]", "Büyük Gladdens Kutusu Tarifi[e]" },
        { "Large Shrew[e]", "Büyük Sivrifare[e]" },
        { "Large Woodmen Totem Recipe[e]", "Büyük Orman İnsanları Totemi Tarifi[e]" },
        { "Lasgalen Grey Owl", "Lasgalen Gri Baykuşu" },
        { "Leaf-fall Kite", "Yaprak Dökümü Uçurtması" },
        { "Leafy Green Snake", "Yapraklı Yeşil Yılan" },
        { "Leaping Fish Kite[e]", "Sıçrayan Balık Uçurtması[e]" },
        { "Legacy Bundle Housing Kit[e]", "Miras Ev Kiti[e]" },
        { "Legacy of Morgoth Treasured Carry-all Selection Box[e]", "Morgoth'un Değerli Çoklu Çanta Seçim Kutusu[e]" },
        { "Legendary Coffer of Glorious Memories of Gondor[e]", "Efsanevi Sandık Şanlı Anıları Gondor[e]" },
        { "Legendary Coffer of the Eerie Apothecary Housing Bundle[e]", "Efsanevi Sandık Tekinsiz Eczacı Ev Paketi[e]" },
        { "Legendary Coffer of the Nautical Housing Collection[e]", "Efsanevi Sandık Denizcilik Ev Koleksiyonu[e]" },
        { "Legendary Coffer of the Outdoor Market[e]", "Efsanevi Sandık Açık Hava Pazar[e]" },
        { "Legendary Coffer of Umbari Furnishings[s]", "Efsanevi Sandık Umbari Döşemeleri[s]" },
        { "Legendary Deep Places Memoir Wardrobe Cosmetics[ps]", "Efsanevi Derin Yerler Hatırası Gardırop Kozmetikleri[ps]" },
        { "Lhingris Crawler", "Lhingris Sürüngeni" },
        { "Lhingris Wormling", "Lhingris Solucancığı" },
        { "Library Corgi", "Kütüphane Korgi" },
        { "Light Armour of the Vales Recipe[E]", "Vadilerin Hafif Zırh Tarifi[E]" },
        { "Light Brown Goat", "Açık Kahverengi Keçi" },
        { "Lion Cub", "Aslan Yavru" },
        { "Little Brown Pig", "Küçük Kahverengi Domuz" },
        { "Little Deep Toad", "Küçük Derin Karakurbağası" },
        { "Little Kid", "Küçük Oğlak" },
        { "Little Mûmak", "Küçük Mûmak" },
        { "Little Tundra Cub[e]", "Küçük Tundra Yavru[e]" },
        { "Lively Slug", "Canlı Sümüklüböcek" },
        { "Loyal Goose of Gondor[e]", "Sadık Kaz Gondor[e]" },
        { "Loyal Knight Patron's Luxuriant Wardrobe Cosmetics[ps]", "Loyal Knight Patron's Gösterişli Gardırop Kozmetikleri[ps]" },
        { "Loyal Swan-knight", "Sadık Kuğu Şövalyesi" },
        { "Loyal Turtle", "Sadık Kaplumbağa" },
        { "Lush Grodbog Protector[e]", "Gür Grodbog Koruyucusu[e]" },
        { "Lyndelby Homestead", "Lyndelby Çiftliği" },
        { "Lyndelby Visitors[ps]", "Lyndelby Ziyaretçileri[ps]" },
        { "Maned Lion", "Yeleli Aslan" },
        { "Maple Kite", "Akçaağaç Uçurtma" },
        { "Marble Mûmak Calf[e]", "Mermer Mûmak Buzağısı[e]" },
        { "Marsh Crocodile Hatchling[e]", "Bataklık Timsah Yavrusu[e]" },
        { "Marsh Frog", "Bataklık Kurbağa" },
        { "Marsh Scorpion[e]", "Bataklık Akrep[e]" },
        { "Medium Armour of the Vales Recipe[E]", "Vadilerin Orta Zırh Tarifi[E]" },
        { "Medium Carry-all selection box[e]", "Orta Çoklu Çanta Seçim Kutusu[e]" },
        { "Medium Woodmen Totem Recipe[e]", "Orta Orman İnsanları Totemi Tarifi[e]" },
        { "Melted Beeswax Candle Recipe[e]", "Eritilmiş Balmumu Mumu Tarifi[e]" },
        { "Merrymaking Hamster", "Şenlik Hamster" },
        { "Midnight Dragon Kite", "Geceyarısı Ejderhası Uçurtması" },
        { "Midsummer Wreath - Selection Box[e]", "Yaz Ortası Çelengi Seçim Kutusu[e]" },
        { "Midsummer's Comet Kite", "Yaz Ortası Kuyruklu Yıldızı Uçurtması" },
        { "Miniature Grodbog Warrior", "Minyatür Grodbog Savaşçısı" },
        { "Mirkwood Patron's Luxuriant Wardrobe Cosmetics[s]", "Kuyutorman Patron's Gösterişli Gardırop Kozmetikleri[s]" },
        { "Mirkwood Sabre-cat[e]", "Kuyutorman Kılıçdişli Kedi[e]" },
        { "Moonstone Drakeling[e]", "Aytaşı Ejderha Yavrusu[e]" },
        { "Mordor Snake", "Mordor Yılan" },
        { "Moria Reclamation Package[e]", "Moria Yeniden Fetih Paketi[e]" },
        { "Moss-covered Tomb[e]", "Yosunlu Mezar[e]" },
        { "Moth Kite", "Güve Uçurtması" },
        { "Mottled Craban", "Alacalı Craban" },
        { "Mottled Goat Kid", "Alacalı Keçi Oğlak" },
        { "Mottled Mirkwood Doe[f]", "Alacalı Kuyutorman Dişi Geyik[f]" },
        { "Mottled Mirkwood Fawn[e]", "Alacalı Kuyutorman Geyik Yavrusu[e]" },
        { "Mottled Mirkwood Stag[m]", "Alacalı Kuyutorman Geyik[m]" },
        { "Mottled Vulture[e]", "Alacalı Akbaba[e]" },
        { "Mountaineering Donkey", "Dağcı Eşek" },
        { "Mûrai Herding Dog[e]", "Mûrai Çoban Köpeği[e]" },
        { "Mushroom Hunter's Corgi[e]", "Mantar Avcısının Korgisi[e]" },
        { "Mushroom Hunter's Frog[e]", "Mantar Avcısının Kurbağası[e]" },
        { "Mushroom Nether-hound", "Mantarlı Öte Tazısı" },
        { "Mysterious Celebration Pig", "Gizemli Kutlama Domuz" },
        { "Nautical Housing Collection[e]", "Denizcilik Ev Koleksiyonu[e]" },
        { "Needle of Many Leagues[s]", "İğne Birçok Fersah[s]" },
        { "Nether-hound", "Öte Tazısı" },
        { "Night Sky Craban", "Gece Gökyüzü Craban" },
        { "Night Squirrel", "Gece Sincap" },
        { "Night Swan", "Gece Kuğu" },
        { "Night-born Slime[e]", "Gece Doğumlu Balçık[e]" },
        { "Noble Eagle Kite", "Asil Kartal Uçurtması" },
        { "Noble Starling", "Asil Sığırcık" },
        { "Oaken Kite", "Meşe Uçurtma" },
        { "Obsidian Deep-claw Whelp[v]", "Obsidyen Derin Pençe Yavrusu[v]" },
        { "Old Rattlepacks", "Eski Gürültü Sürüsü" },
        { "Orange Glow Worm", "Turuncu Işıltılı Solucan" },
        { "Orange Wyandotte Chicken[e]", "Turuncu Wyandotte Tavuk[e]" },
        { "Outdoor Market Housing Collection[v]", "Açık Hava Pazar Ev Koleksiyonu[v]" },
        { "Overgrown Boglurker[v]", "Aşırı Büyümüş Bataklık Pusucusu[v]" },
        { "Pale Deep-claw Whelp[e]", "Soluk Derin Pençe Yavrusu[e]" },
        { "Pale Scorpion[e]", "Soluk Akrep[e]" },
        { "Pale Zizanu[e]", "Soluk Zizanu[e]" },
        { "Parrot", "Papağan" },
        { "Parrot of Darkness", "Karanlık Papağanı" },
        { "Parrot of Light", "Işık Papağanı" },
        { "Parrot of the Fiery Sands", "Ateşli Kumların Papağanı" },
        { "Parrot of Umbar Baharbêl", "Umbar Papağanı Baharbêl" },
        { "Patron's Luxuriant Wardrobe Cosmetics of Promised Allies[ps]", "Patron's Gösterişli Gardırop Kozmetikleri Vaat Edilen Müttefikler[ps]" },
        { "Patron's Luxuriant Wardrobe Cosmetics of the Gilded Caravan[p]", "Patron's Gösterişli Gardırop Kozmetikleri Yaldızlı Kervan[p]" },
        { "Patron's Luxuriant Wardrobe Cosmetics of the Rohirrim[e]", "Patron's Gösterişli Gardırop Kozmetikleri Rohirrim[e]" },
        { "Patron's Luxuriant Wardrobe Cosmetics of the Sands[s]", "Patron's Gösterişli Gardırop Kozmetikleri Kumlar[s]" },
        { "Pebbled Snake", "Çakıllı Yılan" },
        { "Perfect Curl Garden Snail", "Mükemmel Kıvrımlı Bahçe Salyangozu" },
        { "Pet Harness[s]", "Evcil Hayvan Koşumu[s]" },
        { "Picnic Pony", "Piknik Midilli" },
        { "Pile of Decorations[s]", "Dekorasyon Yığını[s]" },
        { "Pink Pig", "Pembe Domuz" },
        { "Pink-beak Cave-claw[e]", "Pembe Gagalı Mağara Pençesi[e]" },
        { "Pinto Rabbit", "Alaca Tavşan" },
        { "Pitch-dark Scorpion[e]", "Zifiri Karanlık Akrep[e]" },
        { "Plain Shrew[e]", "Düz Sivrifare[e]" },
        { "Plateau Mole-rat", "Yayla Köstebek Faresi" },
        { "Poinsettia-wreathed Huorn", "Atatürk Çiçeği Taçlı Huorn" },
        { "Poisonous Grodbog Protector[e]", "Zehirli Grodbog Koruyucusu[e]" },
        { "Pond Frog", "Gölet Kurbağası" },
        { "Pony of Bounty", "Armağan Midillisi" },
        { "Pony of the Autumn Sun", "Sonbahar Güneşi Midillisi" },
        { "Pony of Umbar[e]", "Umbar Midillisi[e]" },
        { "Potato Farmer's Fine Cow[e]", "Patates Çiftçisinin Seçkin İneği[e]" },
        { "Prepared Corgi", "Hazır Korgi" },
        { "Present-bearing Pet Pony", "Hediye Taşıyan Evcil Midilli" },
        { "Proud Lioness", "Gururlu Dişi Aslan" },
        { "Pumpkin Huorn[e]", "Kabak Huornu[e]" },
        { "Pure Seagull", "Saf Martı" },
        { "Purple Chimes Recipe[e]", "Mor Çanlar Tarifi[e]" },
        { "Purple Firefly", "Mor Ateşböceği" },
        { "Quintessential Fawn[e]", "Benzersiz Geyik Yavrusu[e]" },
        { "Rain-cloud", "Yağmur Bulutu" },
        { "Rakish Feline", "Çapkın Kedigiller" },
        { "Raspberry Slime[e]", "Ahududu Balçığı[e]" },
        { "Rat King", "Sıçan Kralı" },
        { "Rat-catcher Cat", "Fare Avcısı Kedi" },
        { "Red and Blue Chimes Recipe[e]", "Kırmızı ve Mavi Çanlar Tarifi[e]" },
        { "Red Beetle", "Kırmızı Böcek" },
        { "Red Chicken[e]", "Kırmızı Tavuk[e]" },
        { "Red Eagle", "Kırmızı Kartal" },
        { "Red Firefly", "Kırmızı Ateşböceği" },
        { "Red Fox", "Kırmızı Tilki" },
        { "Red Gecko", "Kırmızı Geko" },
        { "Red Salamander", "Kırmızı Semender" },
        { "Red Snake", "Kırmızı Yılan" },
        { "Red Squirrel", "Kırmızı Sincap" },
        { "Redstone Mûmak Calf[e]", "Kızıltaş Mûmak Buzağısı[e]" },
        { "Regal Grove Doe[f]", "Görkemli Koruluk Dişi Geyik[f]" },
        { "Regal Grove Fawn[e]", "Görkemli Koruluk Geyik Yavrusu[e]" },
        { "Regal Grove Stag[m]", "Görkemli Koruluk Geyik[m]" },
        { "Ritual Pedestal[E]", "Törensel Kaide[E]" },
        { "Rivendell Homestead", "Ayrıkvadi Çiftliği" },
        { "Rohan Aurochs", "Rohan Yaban Sığırı" },
        { "Rohan Housing Set[e]", "Rohan Ev Seti[e]" },
        { "Rohirric Follower", "Rohir Yoldaşı" },
        { "Rose-coloured Mûmak Calf[e]", "Gül Renkli Mûmak Buzağısı[e]" },
        { "Ruby Drakeling[e]", "Yakut Ejderha Yavrusu[e]" },
        { "Ruby Sand Worm", "Yakut Kum Solucan" },
        { "Ruby Worm[e]", "Yakut Solucan[e]" },
        { "Russet Corgi", "Kızıl Kahverengi Korgi" },
        { "Russet Hedgehog", "Kızıl Kahverengi Kirpi" },
        { "Rust Corgi", "Pas Korgi" },
        { "Rust Slime[e]", "Pas Balçığı[e]" },
        { "Rustflake Dust Devil", "Pas Pullu Toz Şeytanı" },
        { "Rusty Mûrai Herding Dog[e]", "Paslı Mûrai Çoban Köpeği[e]" },
        { "Sack of Mail[E]", "Posta Çuvalı[E]" },
        { "Sand-flies", "Kum Sinekleri" },
        { "Sandpiper[e]", "Kum Kuşu[e]" },
        { "Sapphire Drakeling[e]", "Safir Ejderha Yavrusu[e]" },
        { "Sapphire Neekerbreeker", "Safir Neekerböceği" },
        { "Scrapper Chicken[e]", "Çöpçü Tavuk[e]" },
        { "Sculpture Garden Housing Items with Elvish Pavilion[ps]", "Elf Köşklü Heykel Bahçesi Ev Eşyaları[ps]" },
        { "Sea-borne Slime[e]", "Denizden Gelen Balçık[e]" },
        { "Sea-farer's Supplemental Essence of Fate[e]", "Denizcinin Ek Özü Kader[e]" },
        { "Sea-farer's Supplemental Essence of Vitality[e]", "Denizcinin Ek Özü Zindelik[e]" },
        { "Sea-side Kite[e]", "Deniz Kıyısı Uçurtması[e]" },
        { "Sea-side Sand-lurker", "Deniz Kıyısı Kum Pusucusu" },
        { "Seasonal Winter Tree - Selection Box[e]", "Mevsimlik Kış Ağacı Seçim Kutusu[e]" },
        { "Sentinel-in-training", "Eğitimdeki Muhafız" },
        { "Sewer Rat", "Kanalizasyon Sıçanı" },
        { "Shade-born Zizanu[e]", "Gölge Doğumlu Zizanu[e]" },
        { "Shadow Cat[e]", "Gölge Kedi[e]" },
        { "Shadow Grim", "Gölge Kasvetlisi" },
        { "Shadow Hedgehog[e]", "Gölge Kirpi[e]" },
        { "Shadow Lion[e]", "Gölge Aslan[e]" },
        { "Shadow Nether-hound[e]", "Gölge Öte Tazısı[e]" },
        { "Shadow Raven[e]", "Gölge Kuzgun[e]" },
        { "Shadow Spider[e]", "Gölge Örümcek[e]" },
        { "Shepherd Dog", "Çoban Köpeği" },
        { "Shobdo the Little Mûmak", "Küçük Mûmak Shobdo" },
        { "Sienna Goat", "Kestane Keçi" },
        { "Sienna Hamster", "Kestane Hamster" },
        { "Silver Chipmunk", "Gümüş Çizgili Sincap" },
        { "Silver Donkey", "Gümüş Eşek" },
        { "Silver Dragon Kite", "Gümüş Ejderha Uçurtması" },
        { "Silver Goat Kid", "Gümüş Keçi Oğlak" },
        { "Silver Housing Decorations of Yules Past - Selection Box[e]", "Geçmiş Yule'un Gümüş Ev Dekorasyonları Seçim Kutusu[e]" },
        { "Silver Scorpion[e]", "Gümüş Akrep[e]" },
        { "Silverback Badger", "Gümüş Sırtlı Porsuk" },
        { "Sitaka", "Sitaka Yoldaşı" },
        { "Sketches of Azagath Sea-shadow[p]", "Deniz Gölgesi Azagath Eskizleri[p]" },
        { "Sketches of Belondor of Langstrand[p]", "Langstrandlı Belondor Eskizleri[p]" },
        { "Sketches of Hármelak Golden-hand[p]", "Altın Elli Hármelak Eskizleri[p]" },
        { "Sketches of Khôltekh the Cunning[p]", "Kurnaz Khôltekh Eskizleri[p]" },
        { "Sketches of Nakási Wave-reaper and Tumúldo Fierce-water[p]", "Dalgabiçen Nakási ve Sertsu Tumúldo Eskizleri[p]" },
        { "Sketches of Rothog the Storm[p]", "Fırtına Rothog Eskizleri[p]" },
        { "Sketches of Tatháta the Beast[p]", "Yaratık Tatháta Eskizleri[p]" },
        { "Skittish Black Horse", "Ürkek Kara At" },
        { "Skulking Worm[e]", "Gizlenen Solucan[e]" },
        { "Sky of a Perfect Day Kite", "Mükemmel Günün Gökyüzü Uçurtması" },
        { "Slate Aurochs", "Kayrak Yaban Sığırı" },
        { "Slate Jerboa", "Kayrak Arap Tavşanı" },
        { "Sleek Fox", "Zarif Tilki" },
        { "Small box of Cockscomb Recipe[e]", "Küçük Horozibiği Kutusu Tarifi[e]" },
        { "Small box of Gladdens Recipe[e]", "Küçük Gladdens Kutusu Tarifi[e]" },
        { "'Small' Woodmen Totem Recipe[e]", "Küçük Orman İnsanları Totemi Tarifi[e]" },
        { "Smaug Kite", "Smaug Uçurtması" },
        { "Smoky-grey Cat", "Dumanlı Gri Kedi" },
        { "Snow Not-so-grim", "Pek de Kasvetli Olmayan Kar Yaratığı" },
        { "Snow Owl", "Kar Baykuşu" },
        { "Snow-covered Aurochs", "Karla Kaplı Yaban Sığırı" },
        { "Snow-dusted Farm-yard Horse[e]", "Kar Tozlu Çiftlik Atı[e]" },
        { "Snowy Barn Owl", "Karlı Ahır Baykuşu" },
        { "Snowy Evening Pig[e]", "Karlı Akşam Domuz[e]" },
        { "Snowy Fangorn Huorn", "Karlı Fangorn Huornu" },
        { "Snowy Mountain Eagle", "Karlı Dağ Kartalı" },
        { "Soaring Bird Kite", "Süzülen Kuş Uçurtması" },
        { "Songbird", "Ötücü Kuş" },
        { "Soot-feathered Crow", "Kurum Tüylü Karga" },
        { "Sophisticated Chaffinch[e]", "Zarif İspinoz[e]" },
        { "Sophisticated Magpie[e]", "Zarif Saksağan[e]" },
        { "Spiky Avanc", "Dikenli Avank" },
        { "Spirit Bear[e]", "Ruh Ayı[e]" },
        { "Spooky Barrow-lurker", "Ürkütücü Tümülüs Pusucusu" },
        { "Spooky Jackdaw", "Ürkütücü Küçük Karga" },
        { "Spotted Corgi", "Benekli Korgi" },
        { "Spotted Hamster", "Benekli Hamster" },
        { "Spotted Jerboa", "Benekli Arap Tavşanı" },
        { "Spotted Pig", "Benekli Domuz" },
        { "Spotted Shrew[e]", "Benekli Sivrifare[e]" },
        { "Spotted Woodland Fawn", "Benekli Ormanlık Geyik Yavrusu" },
        { "Spring Copse Stag[m]", "İlkbahar Koruluğu Geyiği[m]" },
        { "Spring Pheasant - Female", "İlkbahar Sülün Dişi" },
        { "Spring Pheasant - Male", "İlkbahar Sülün Erkek" },
        { "Steed Halter[e]", "Küheylan Yuları[e]" },
        { "Steed of Ethuil", "Ethuil'in Küheylanı" },
        { "Steed of Nárië", "Nárië'nin Küheylanı" },
        { "Steed of New Bloom", "Yeni Çiçeklenme Küheylanı" },
        { "Steed of Odogil", "Odogil'in Küheylanı" },
        { "Steed of Spring Gardens", "İlkbahar Bahçeleri Küheylanı" },
        { "Steed of the Anórien Autumn", "Anórien Sonbaharı Küheylanı" },
        { "Steed of the Eldar", "Eldar'ın Küheylanı" },
        { "Steed of the Gloaming Autumn", "Alacakaranlık Sonbaharı Küheylanı" },
        { "Steed of the Ithilien Winter", "Ithilien Kışı Küheylanı" },
        { "Steed of the Moon Moth", "Ay Güvesi Küheylanı" },
        { "Steed of the North Ithilien Wilds", "Kuzey Ithilien Yabanlarının Küheylanı" },
        { "Steed of the Ship-kings", "Gemi Krallarının Küheylanı" },
        { "Steed of the Summer Sea", "Yaz Denizi Küheylanı" },
        { "Steed of the Unflagging Dragon", "Yılmayan Ejderhanın Küheylanı" },
        { "Steed of the White City", "Beyaz Şehrin Küheylanı" },
        { "Steed of the Woodland Realm", "Ormanlık Diyarın Küheylanı" },
        { "Steed of the Yield", "Hasat Küheylanı" },
        { "Steed of Wedmath Celebration", "Wedmath Kutlaması Küheylanı" },
        { "Steed of Winter Winds", "Kış Rüzgârları Küheylanı" },
        { "Steed of Winter's Light", "Kış Işığının Küheylanı" },
        { "Stone Mûmak Calf[e]", "Taş Mûmak Buzağısı[e]" },
        { "Stool - Vales of Anduin Recipe[e]", "Anduin Vadileri Taburesi Tarifi[e]" },
        { "Storm-cloud", "Fırtına Bulutu" },
        { "Storm-wing Kite", "Fırtına Kanadı Uçurtması" },
        { "Stowaway Rat", "Kaçak Sıçan" },
        { "Striped Deep-claw Whelp[e]", "Çizgili Derin Pençe Yavrusu[e]" },
        { "Striped Grodbog Protector[e]", "Çizgili Grodbog Koruyucusu[e]" },
        { "Striped Jerboa", "Çizgili Arap Tavşanı" },
        { "Striped Oryx[e]", "Çizgili Oryx[e]" },
        { "Striped Pelennor Pig", "Çizgili Pelennor Domuz" },
        { "Striped Snake", "Çizgili Yılan" },
        { "Stripey Bat", "Çizgili Yarasa" },
        { "Sublime Boar", "Yüce Yaban Domuzu" },
        { "Sublime Piglet", "Yüce Domuz Yavrusu" },
        { "Summer Concert Firefly", "Yaz Konser Ateşböceği" },
        { "Summer Flower Kite", "Yaz Çiçeği Uçurtması" },
        { "Sunflower Kite", "Ayçiçeği Uçurtması" },
        { "Sun-kissed Supplemental Essence of Fate[e]", "Sun-kissed Ek Özü Kader[e]" },
        { "Sun-kissed Supplemental Essence of Vitality[e]", "Sun-kissed Ek Özü Zindelik[e]" },
        { "Sun-laden Mûmak Calf[e]", "Güneş Yüklü Mûmak Buzağısı[e]" },
        { "Sunny Summer Kite", "Güneşli Yaz Uçurtması" },
        { "Sunstone Drakeling[e]", "Güneştaşı Ejderha Yavrusu[e]" },
        { "Superior River Hobbit Cosmetics[ps]", "Superior River Hobbit Kozmetikleri[ps]" },
        { "Swan[e]", "Kuğu[e]" },
        { "Swan-knight Rider", "Kuğu Şövalyesi Binicisi" },
        { "Swarm of Bees", "Arı Sürüsü" },
        { "Tame Gundabad Bat", "Evcilleştirilmiş Gundabad Yarasası" },
        { "Tame Hyena[e]", "Evcilleştirilmiş Sırtlan[e]" },
        { "Tame Wildwood Huorn", "Evcilleştirilmiş Yabanorman Huornu" },
        { "Tame Wildwood Tusker", "Evcilleştirilmiş Yabanorman Fildişilisi" },
        { "Tamed Variag Hound", "Evcilleştirilmiş Variag Tazısı" },
        { "Tan Bat", "Taba Yarasa" },
        { "Tan Fox", "Taba Tilki" },
        { "Tan Sheep", "Taba Koyun" },
        { "Tan Wolf-dog", "Taba Kurt Köpeği" },
        { "Tan-back Cave-claw[e]", "Taba Sırtlı Mağara Pençesi[e]" },
        { "Tanglemane", "Düğülyele" },
        { "Tattered Bat", "Yırtık Yarasa" },
        { "Taupe Hamster", "Boz Hamster" },
        { "Tawny Aurochs", "Boz Yaban Sığırı" },
        { "Tawny Oryx[e]", "Boz Oryx[e]" },
        { "Teacup Goat Kid", "Fincan Keçi Oğlak" },
        { "Terror of the Caverns[s]", "Mağaraların Dehşeti[s]" },
        { "Terror of the Sands[s]", "Kumların Dehşeti[s]" },
        { "The Allure of Umbar Baharbêl[n]", "Umbar Baharbêl'in Cazibesi[n]" },
        { "The Farmer's Second Favourite Steed", "Çiftçinin İkinci Gözdesi Küheylanı" },
        { "The King's Pony", "Kralın Midillisi" },
        { "Thicket Mole-rat", "Çalılık Köstebek Faresi" },
        { "Thin Woodmen Hitching Post Recipe[e]", "İnce Orman İnsanları Bağlama Direği Tarifi[e]" },
        { "Three Peaks Large Carry-all selection box[e]", "Üç Doruk Büyük Çoklu Çanta Seçim Kutusu[e]" },
        { "Thrush", "Ardıç Kuşu" },
        { "Tidal Dune-lurker", "Gelgit Kumul Pusucusu" },
        { "Timeless Elf-hawk[e]", "Zamansız Elf Doğanı[e]" },
        { "Timeless Patron's Luxuriant Wardrobe Cosmetics of the Noldor[p]", "Timeless Patron's Gösterişli Gardırop Kozmetikleri Noldor[p]" },
        { "Toffee Goat Kid", "Karamel Keçi Oğlak" },
        { "Toffee Mûrai Herding Dog[e]", "Karamel Mûrai Çoban Köpeği[e]" },
        { "Topaz Neekerbreeker", "Topaz Neekerböceği" },
        { "Toxic Frogling", "Zehirli Kurbağacık" },
        { "Treasure Grim[e]", "Hazine Kasvetlisi[e]" },
        { "Treasured Jackal[e]", "Değerli Çakal[e]" },
        { "Treasure-laden Donkey", "Hazine Yüklü Eşek" },
        { "Treasure-seeking Cave-claw[e]", "Hazine Arayan Mağara Pençesi[e]" },
        { "Tri-colour Corgi", "Üç Renkli Korgi" },
        { "Troll-hoard Debris[e]", "Trol Hazinesi Enkazı[e]" },
        { "Trout Kite", "Alabalık Uçurtması" },
        { "Truffle Cluster Recipe[e]", "Yer Mantarı Kümesi Tarifi[e]" },
        { "Turquoise Snake", "Turkuaz Yılan" },
        { "Twilight Fire-fly", "Alacakaranlık Ateşböceği" },
        { "Twilight Mûmak Calf[e]", "Alacakaranlık Mûmak Buzağısı[e]" },
        { "Two-toned Sheep", "İki Renkli Koyun" },
        { "Umbar Baharbêl Decorative Swing Signs - Selection Box[v]", "Umbar Baharbêl Dekoratif Salıncak Tabelaları Seçim Kutusu[v]" },
        { "Umbar Housing Collection[v]", "Umbar Ev Koleksiyonu[v]" },
        { "Umbari Huorn", "Umbar Huornu" },
        { "Umber Goat", "Esmer Keçi" },
        { "Umber Nether-hound", "Esmer Öte Tazısı" },
        { "Unlocked Door[v]", "Açık Kapı[v]" },
        { "Verdant Deep-claw Whelp[e]", "Yemyeşil Derin Pençe Yavrusu[e]" },
        { "Verdant Grodbog Queen[f]", "Yemyeşil Grodbog Kraliçesi[f]" },
        { "Very Fancy Cat", "Çok Şık Kedi" },
        { "Vibrant Spotted Boglurker[e]", "Canlı Benekli Bataklık Pusucusu[e]" },
        { "Vigilant Cobra[e]", "Tetikte Kobra[e]" },
        { "Vivid Green Snake", "Canlı Yeşil Yılan" },
        { "Wall-mounted Bear-claw Club of the Vales Recipe[e]", "Vadilerin Duvara Asılan Ayı Pençesi Sopası Tarifi[e]" },
        { "Wall-mounted Captain's Shield of the Vales Recipe[e]", "Vadilerin Duvara Asılan Kumandan Kalkanı Tarifi[e]" },
        { "Wall-mounted Crossbow of the Vales Recipe[e]", "Vadilerin Duvara Asılan Tatar Yayı Tarifi[e]" },
        { "Wall-mounted Great-axe of the Vales Recipe[e]", "Vadilerin Duvara Asılan Büyük Balta Tarifi[e]" },
        { "Wall-mounted Greatsword of the Vales Recipe[e]", "Vadilerin Duvara Asılan Büyük Kılıç Tarifi[e]" },
        { "Wall-mounted Guardian's Shield of the Vales Recipe[e]", "Vadilerin Duvara Asılan Muhafız Kalkanı Tarifi[e]" },
        { "Wall-mounted Halberd of the Vales Recipe[e]", "Vadilerin Duvara Asılan Balta-mızrak Tarifi[e]" },
        { "Wall-mounted Hammer, Knife, and Axe of the Vales Recipe[e]", "Vadilerin Duvara Asılan Çekiç, Bıçak ve Balta Tarifi[e]" },
        { "Wall-mounted Mace of the Vales Recipe[e]", "Vadilerin Duvara Asılan Topuz Tarifi[e]" },
        { "Wall-mounted Minstrel's Shield of the Vales Recipe[e]", "Vadilerin Duvara Asılan Ozan Kalkanı Tarifi[e]" },
        { "Wall-mounted Rune-stone of the Vales Recipe[e]", "Vadilerin Duvara Asılan Rün Taşı Tarifi[e]" },
        { "Wall-mounted Spear of the Vales Recipe[e]", "Vadilerin Duvara Asılan Mızrak Tarifi[e]" },
        { "Wall-mounted Staff of the Vales Recipe[e]", "Vadilerin Duvara Asılan Asa Tarifi[e]" },
        { "Wall-mounted Sword of the Vales Recipe[e]", "Vadilerin Duvara Asılan Kılıç Tarifi[e]" },
        { "Wall-mounted Warden's Shield of the Vales Recipe[e]", "Vadilerin Duvara Asılan Gözcü Kalkanı Tarifi[e]" },
        { "Water Buffalo Bull", "Su Mandası Boğası" },
        { "Water Buffalo Calf", "Su Mandası Buzağısı" },
        { "Water Buffalo Cow", "Su Mandası İneği" },
        { "Well-laden Mûmak Calf[e]", "İyi Yüklü Mûmak Buzağısı[e]" },
        { "Well-supplied Hound", "İyi Donanımlı Tazı" },
        { "Well-travelled Turtle", "Çok Gezmiş Kaplumbağa" },
        { "Whimsical Woodland Critters", "Tuhaf Orman Yaratıkları" },
        { "Whistle[E]", "Düdük[E]" },
        { "White Chicken[e]", "Beyaz Tavuk[e]" },
        { "White Fox", "Beyaz Tilki" },
        { "White Goose", "Beyaz Kaz" },
        { "White Hamster", "Beyaz Hamster" },
        { "White Hare", "Beyaz Yaban Tavşanı" },
        { "White Heartwood Fawn", "Beyaz Özodun Geyik Yavrusu" },
        { "White Huorn", "Beyaz Huorn" },
        { "White Peacock", "Beyaz Tavuskuşu" },
        { "White Peahen", "Beyaz Dişi Tavuskuşu" },
        { "White Puppy", "Beyaz Yavru Köpek" },
        { "White Squirrel", "Beyaz Sincap" },
        { "White Swan[e]", "Beyaz Kuğu[e]" },
        { "White Wolf-dog", "Beyaz Kurt Köpeği" },
        { "White-headed Hawk", "Beyaz Başlı Şahin" },
        { "White-necked Doe[f]", "Beyaz Boyunlu Dişi Geyik[f]" },
        { "White-necked Fawn[e]", "Beyaz Boyunlu Geyik Yavrusu[e]" },
        { "White-necked Stag[m]", "Beyaz Boyunlu Geyik[m]" },
        { "Wild Black Donkey", "Vahşi Kara Eşek" },
        { "Wild Chocolate Donkey", "Vahşi Çikolata Eşek" },
        { "Wild Cinnamon Donkey", "Vahşi Tarçın Eşek" },
        { "Wild Grey Donkey", "Vahşi Gri Eşek" },
        { "Wild Spotted Donkey", "Vahşi Benekli Eşek" },
        { "Wildflower[e]", "Yabani Çiçek[e]" },
        { "Wildfowl Kite", "Yaban Kuşu Uçurtması" },
        { "Willem Whisker", "Willem Bıyık" },
        { "Willem's Cub", "Willem'in Yavrusu" },
        { "Wily Macaque", "Kurnaz Makak" },
        { "Windfell Owl[e]", "Rüzgâr Ovası Baykuş[e]" },
        { "Windfells Goat", "Windfells Keçisi" },
        { "Wine-red Snake", "Şarap Kırmızısı Yılan" },
        { "Winter Celebration Pig", "Kış Kutlama Domuz" },
        { "Winter Dove Kite", "Kış Kumrusu Uçurtması" },
        { "Winter's Flower", "Kış Çiçeği" },
        { "Winter's Wind", "Kış Rüzgârı" },
        { "Wintertide Steed", "Kış Şenliği Küheylanı" },
        { "Wooden Chimes Recipe[e]", "Ahşap Çanlar Tarifi[e]" },
        { "Woodland Doe", "Ormanlık Dişi Geyik" },
        { "Woodland Hart", "Ormanlık Erkek Geyiği" },
        { "Woodland Rabbit", "Ormanlık Tavşan" },
        { "World Consolidation Giftbox[e]", "Dünya Birleştirme Hediye Kutusu[e]" },
        { "Worm Nest[e]", "Solucan Yuvası[e]" },
        { "Wose Housing Set[e]", "Wose Ev Seti[e]" },
        { "Yellow Snake", "Sarı Yılan" },
        { "You must acquire the housing decoration: Nazgûl Ring to earn this across your account.", "You must acquire Ev Dekorasyon: Nazgûl Ring to earn this across your account." },
        { "You must acquire the Ride of the Nazgûl housing decoration.", "You must acquire Ride Nazgûl Ev Dekorasyon." },
        { "Young Brown Oryx[e]", "Genç Kahverengi Oryx[e]" },
        { "Young Moose", "Genç Sığın" },
        { "Young Striped Oryx[e]", "Genç Çizgili Oryx[e]" },
        { "Young Tawny Oryx[e]", "Genç Boz Oryx[e]" },
        { "Yule Rabbit", "Yule Tavşanı" },
        { "Yule Tree Huorn", "Yule Ağacı Huornu" },
        { "Yule Wreath - Selection Box[e]", "Yule Çelengi Seçim Kutusu[e]" },
        { "Zajâni Council Housing Collection[e]", "Zajâni Meclisi Ev Koleksiyonu[e]" },
        { "Zajâni Gallery Housing Collection[e]", "Zajâni Galeri Ev Koleksiyonu[e]" },
    };

    public static string ExactForEnglish(string source)
    {
        if (source == null) return null;
        return Exact.TryGetValue(source, out string target) ? target : null;
    }
}
